- hosts: nagios-patient
  vars_files:
    - vars/main.yml
    - vars/database.yml
  # user: intentionally blank
  remote_user: "{{ deploy }}"
  roles:
    - { role: ansible-nrpe}
    - { role: apache}
